name: "CI/CD Security Testing with CodeQL & Docker"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 1️⃣ Static Analysis (SAST) dengan CodeQL
  codeql-analysis:
    name: "Static Code Analysis (CodeQL)"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: [javascript]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # 2️⃣ Dynamic Security Test (DAST) dengan OWASP ZAP
  zap-scan:
    name: "Dynamic Security Test (OWASP ZAP)"
    runs-on: ubuntu-latest
    needs: codeql-analysis
    steps:
      - name: Start DVWA with Docker
        run: |
          docker run -d --name dvwa -p 8080:80 vulnerables/web-dvwa
          sleep 15  # Tunggu agar DVWA siap

      - name: OWASP ZAP Security Scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080
