name: "Security Testing with CodeQL & OWASP ZAP"

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'  # Jalankan otomatis setiap hari jam 12 siang

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan DVWA dengan OWASP ZAP
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://10.10.1.3:8080
